name: cinemaxappp
description: "Your go to application for movies & tv shows."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  #firebase_core: ^2.27.0
  #firebase_auth: ^4.17.8
  #cloud_firestore: ^4.15.8
  #firebase_storage: ^11.6.9

  # in case the fire base did'nt work ZID HADO
  #firebase_core: ^2.25.0
  #firebase_auth: ^4.16.0
  #cloud_firestore: ^4.14.0
  #firebase_storage: ^11.6.0

  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9

  # Image handling
  image_picker: ^1.0.7
  #image_cropper: ^5.0.1
  image_cropper: ^5.0.1
  path_provider: ^2.1.2

  # Utils
  share_plus: ^7.2.2
  uuid: ^4.3.3

  # State Management
  provider: ^6.1.2

  # UI
  cupertino_icons: ^1.0.8
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  cached_network_image: ^3.3.1
  flutter_rating_bar: ^4.0.1
  shimmer: ^3.0.0

  # HTTP
  http: ^1.2.1
  dio: ^5.4.1

  # Utils
  intl: ^0.19.0
  url_launcher: ^6.2.5
  shared_preferences: ^2.2.2

  # SVG
  flutter_svg: ^2.0.10+1

  # new dependencies
  photo_view: ^0.14.0
  flutter_inappwebview: ^6.0.0
  youtube_player_flutter: ^9.0.4
  # this was the replaced depend youtube_player_flutter: ^8.1.2

  # in case this didn't work
  #flutter_inappwebview: ^6.0.0
  # replace it with this -> flutter_inappwebview: ^5.8.0
  # or othis -> flutter_inappwebview: ^5.7.2+3

  #flutter pub add flutter_inappwebview:^6.0.0
  #flutter pub add youtube_player_flutter:^9.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/cinemax_app_icon.png"
  adaptive_icon_background: "#121212" # Your app's background color
  adaptive_icon_foreground: "assets/icons/cinemax_app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
